# docker-compose.yml
version: '3.8'

services:
  app:
    build: .
    ports:
      - "1040:3000" # Map Port 1040 (host) -> 3000 (container)
    environment:
      - DB_HOST=db
      - DB_USER=postgres
      - DB_PASSWORD=Ms1234
      - DB_NAME=mtoken_db
    depends_on:
      - db
    restart: always

  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Ms1234
      POSTGRES_DB: mtoken_db
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./database.sql:/docker-entrypoint-initdb.d/init.sql # สร้างตารางอัตโนมัติเมื่อเริ่มครั้งแรก

volumes:
  pgdata: